/*

	About: Weapon header
	Author: Foxze

*/

/*----------------------------------------------------------------------------
Functions:
	Public:
		-
	Stock:
		-
Enums:
	-
Global var:
	-
------------------------------------------------------------------------------*/

#if defined _INC_WEAPON_HEADER
	#endinput
#endif
#define _INC_WEAPON_HEADER

/*

	* Defines *

*/

#define WEAPON_NAME_MAX_LENGTH  (19 + 1)
