/*

	About: Quests header
	Author: Foxze

*/

/*----------------------------------------------------------------------------
Functions:
	Public:
		-
	Stock:
		-
Enums:
	-
Global var:
	-
------------------------------------------------------------------------------*/

#if defined _INC_QUESTS_HEADER
	#endinput
#endif
#define _INC_QUESTS_HEADER

/*

	* Defines *

*/

#define QUESTS_MAX					(31)		// Макс. кол-во квестов
#define QUESTS_MAX_PROGRESS			(3)			// Макс. кол-во квестов в процессе
#define QUESTS_MAX_LIST				(10)		// Макс. кол-во квестов в списке

#define QUESTS_MAX_NAME_LENGTH		(50 + 1)
#define QUESTS_MAX_INFO_LENGTH		(250 + 1)