/*
 * |>=============================<|
 * |   About: Room location head   |
 * |   Author: Foxze               |
 * |>=============================<|
 */

/*
 * |>--------------------------------------------<|
 * |                  Functions                   |
 * |>--------------------------------------------<|
 * Public:
	- (None)
 * Stock:
	- (None)
 * |>--------------------------------------------<|
 * |                  Enums                       |
 * |>--------------------------------------------<|
	- (None)
 * |>--------------------------------------------<|
 * |                  Global vars                 |
 * |>--------------------------------------------<|
	- (None)
 */

#if defined _INC_ROOM_LOC_HEAD
	#endinput
#endif
#define _INC_ROOM_LOC_HEAD

/*
 * |>-------------<|
 * |     Enums     |
 * |>-------------<|
 */

enum {
	ROOM_LOC_DESERT = 0,
	ROOM_LOC_ZONE51,
	ROOM_LOC_MILITARYOIL,
	ROOM_LOC_AIRPORT,
	ROOM_LOC_STADIUM
}