/*

	About: Game-modes all include headers
	Author: Foxze

*/

#if defined _INC_GAME_MODES_ALL_HEADERS
	#endinput
#endif
#define _INC_GAME_MODES_ALL_HEADERS

/*

	* Includes *

*/

// Core
#include <sources/game-modes/header>

// Mode None
#include <sources/game-modes/none/header>

// Mode TDM
#include <sources/game-modes/tdm/header>
#include <sources/game-modes/tdm/locations/header>

// Mode DM
#include <sources/game-modes/dm/header>
#include <sources/game-modes/dm/locations/header>

// Mode Room
#include <sources/game-modes/room/header>
#include <sources/game-modes/room/locations/header>

// Mode Example
#include <sources/game-modes/example/header>
#include <sources/game-modes/example/locations/header>