/*
 * |>================================<|
 * |   About: Trading-platform head   |
 * |   Author: Foxze                  |
 * |>================================<|
 */

/*
 * |>--------------------------------------------<|
 * |                  Functions                   |
 * |>--------------------------------------------<|
 * Public:
	- (None)
 * Stock:
	- (None)
 * |>--------------------------------------------<|
 * |                  Enums                       |
 * |>--------------------------------------------<|
	- (None)
 * |>--------------------------------------------<|
 * |                  Global vars                 |
 * |>--------------------------------------------<|
	- (None)
 */

#if defined _INC_TRADING_PLATFORM_HEAD
	#endinput
#endif
#define _INC_TRADING_PLATFORM_HEAD

/*
 * |>---------------<|
 * |     Defines     |
 * |>---------------<|
 */

// Core
#define	TRAD_PLAT_MAX_SHOW_ITEMS		(6)

// Blocks
#define	TRAD_PLAT_MAX_BLOCKS_HEAD		(5)
#define	TRAD_PLAT_MAX_BLOCKS_GLASSES	(3)
#define	TRAD_PLAT_MAX_BLOCKS_MASK		(2)
#define	TRAD_PLAT_MAX_BLOCKS_WATCH		(2)
#define	TRAD_PLAT_MAX_BLOCKS_SKINS		(2)
#define	TRAD_PLAT_MAX_BLOCKS_BANNERS	(2)

// Others
#define	TRAD_PLAT_MAX_LEN_BLOCK_NAME	(15)