/*

	About: Example core header
	Author: Foxze

*/

/*----------------------------------------------------------------------------
Functions:
	Public:
		-
	Stock:
		-
Enums:
	-
Global var:
	-
------------------------------------------------------------------------------*/

#if defined _INC_EXAMPLE_CORE_HEADER
	#endinput
#endif
#define _INC_EXAMPLE_CORE_HEADER

/*

	* Defines *

*/

#define EXAMPLE_MAX_PLAYERS				(10)	// Макс. игроков
#define EXAMPLE_MAX_GAME_SESSIONS		(1)		// Кол-во сессий

#define EXAMPLE_PLAYER_TIMER_RESPAWN	(15)	// Таймер респавна игрока после смерти

#define EXAMPLE_TEAM_NONE				(0)		// Нейтралы