/*

	About: Dina helper header
	Author: Foxze

*/

/*----------------------------------------------------------------------------
Functions:
	Public:
		-
	Stock:
		-
Enums:
	-
Global var:
	-
--------------------------------------------------------------------------------*/

#if defined _INC_DINA_HEADER
	#endinput
#endif
#define _INC_DINA_HEADER

/*

	* Defines *

*/

#define DINA_MAX_HINTS			(20)		// Макс. подсказок от помощника Дины
#define DINA_MAX_TEXT_LENGTH	(350)