/*
 * |>======================<|
 * |   About: Quests head   |
 * |   Author: Foxze        |
 * |>======================<|
 */

/*
 * |>--------------------------------------------<|
 * |                  Functions                   |
 * |>--------------------------------------------<|
 * Public:
	- (None)
 * Stock:
	- (None)
 * |>--------------------------------------------<|
 * |                  Enums                       |
 * |>--------------------------------------------<|
	- (None)
 * |>--------------------------------------------<|
 * |                  Global vars                 |
 * |>--------------------------------------------<|
	- (None)
 */

#if defined _INC_QUESTS_HEAD
	#endinput
#endif
#define _INC_QUESTS_HEAD

/*
 * |>---------------<|
 * |     Defines     |
 * |>---------------<|
 */

#define QUESTS_MAX					(31)		// Max number of quests
#define QUESTS_MAX_PROGRESS			(3)			// Max quests in progress
#define QUESTS_MAX_LIST				(10)		// Max number of quests in the list

#define QUESTS_MAX_NAME_LENGTH		(51)
#define QUESTS_MAX_INFO_LENGTH		(251)