/*

	About: Vehicles header
	Author: Foxze

*/

/*----------------------------------------------------------------------------
Functions:
	Public:
		-
	Stock:
		-
Enums:
	-
Global var:
	-
------------------------------------------------------------------------------*/

#if defined _INC_VEHICLE_HEADER
	#endinput
#endif
#define _INC_VEHICLE_HEADER

/*

	* Defines *

*/

#define VEHICLE_FUEL 				(35)
#define VEHICLE_RESPAWN_TIME 		(100)
#define VEHICLE_TIMER_OLD_DAMAGE	(30)		// Таймер на удаление данных о последнем уроне от игрока
#define VEHICLE_STRING_NAME_LENGTH	(50 + 1)