/*

	About: Trading-platform header
	Author: Foxze

*/

/*----------------------------------------------------------------------------
Functions:
	Public:
		-
	Stock:
		-
Enums:
	-
Global var:
	-
--------------------------------------------------------------------------------*/

#if defined _INC_TRADING_PLATFORM_HEADER
	#endinput
#endif
#define _INC_TRADING_PLATFORM_HEADER

/*

	* Defines *

*/

#define	TRADING_PLAT_MAX_HOW_ITEMS		(6)