/*
 * |>============================<|
 * |   About: Mode Example head   |
 * |   Author: Foxze              |
 * |>============================<|
 */

/*
 * |>--------------------------------------------<|
 * |                  Functions                   |
 * |>--------------------------------------------<|
 * Public:
	- (None)
 * Stock:
	- (None)
 * |>--------------------------------------------<|
 * |                  Enums                       |
 * |>--------------------------------------------<|
	- (None)
 * |>--------------------------------------------<|
 * |                  Global vars                 |
 * |>--------------------------------------------<|
	- (None)
 */

#if defined _INC_EXAMPLE_HEAD
	#endinput
#endif
#define _INC_EXAMPLE_HEAD

/*
 * |>---------------<|
 * |     Defines     |
 * |>---------------<|
 */

#define EXAMPLE_MAX_PLAYERS				(10)	// Max players
#define EXAMPLE_PLAYER_TIMER_RESPAWN	(15)	// Player respawn timer after death

// Team
#define EXAMPLE_TEAM_NONE				(0)		// Neutral