/*

	About: None core header
	Author: Foxze

*/

/*----------------------------------------------------------------------------
Functions:
	Public:
		-
	Stock:
		-
Enums:
	-
Global var:
	-
------------------------------------------------------------------------------*/

#if defined _INC_NONE_CORE_HEADER
	#endinput
#endif
#define _INC_NONE_CORE_HEADER

/*

	* Defines *

*/

#define NONE_MAX_PLAYERS			(1000)	// Макс. игроков в режиме