/*
 * |>=======================<|
 * |   About: Vehicle head   |
 * |   Author: Foxze         |
 * |>=======================<|
 */

/*
 * |>--------------------------------------------<|
 * |                  Functions                   |
 * |>--------------------------------------------<|
 * Public:
	- (None)
 * Stock:
	- (None)
 * |>--------------------------------------------<|
 * |                  Enums                       |
 * |>--------------------------------------------<|
	- (None)
 * |>--------------------------------------------<|
 * |                  Global vars                 |
 * |>--------------------------------------------<|
	- (None)
 */

#if defined _INC_VEHICLE_HEAD
	#endinput
#endif
#define _INC_VEHICLE_HEAD

/*
 * |>---------------<|
 * |     Defines     |
 * |>---------------<|
 */

#define VEHICLE_FUEL 				(35)
#define VEHICLE_RESPAWN_TIME 		(100)
#define VEHICLE_TIMER_LAST_DAMAGE	(30)		// Timer for deleting data about the last damage from the player
#define VEHICLE_LENGTH_NAME			(51)