/*
 * |>=====================<|
 * |   About: Color list   |
 * |   Author: Foxze       |
 * |>=====================<|
 */

#if defined _INC_COLOR_LIST
	#endinput
#endif
#define _INC_COLOR_LIST

/*
 * |>---------------<|
 * |     Defines     |
 * |>---------------<|
 */

/*
 * |>--------<|
 * |   Core   |
 * |>--------<|
 */

// White
#define C_WHITE			0xFFFFFFFF
#define CT_WHITE		"{FFFFFF}"

// Dark white
#define C_DARK_WHITE	0xd4d4d4FF
#define CT_DARK_WHITE	"{d4d4d4}"

// Red
#define C_RED			0xCC0033FF
#define CT_RED			"{CC0033}"

// Blue
#define C_BLUE			0x004DFFFF
#define CT_BLUE			"{004DFF}"

// Light blue
#define C_LIGHT_BLUE	0x3b9de3FF
#define CT_LIGHT_BLUE	"{3b9de3}"

// Green
#define C_GREEN			0x57D643FF
#define CT_GREEN		"{57D643}"

// Orange
#define C_ORANGE		0xFF9900FF
#define CT_ORANGE		"{FF9900}"

// Yellow
#define C_YELLOW		0xFFFF00FF
#define CT_YELLOW		"{FFFF00}"

// Gray
#define C_GREY			0xCCCCCCFF
#define CT_GREY			"{CCCCCC}"

// Violet
#define C_VIOLET		0x4837deFF
#define CT_VIOLET		"{4837de}"

// Emerald
#define C_EMERLAND		0x17e387FF
#define CT_EMERLAND		"{17e387}"

// Tomato
#define C_TOMATO		0xFF6347FF
#define CT_TOMATO		"{FF6347}"

// Carmine
#define C_CARMINE		0xCC1836FF
#define CT_CARMINE		"{CC1836}"

/*
 * |>--------------<|
 * |   TextDraw's   |
 * |>--------------<|
 */

#define TD_C_GREY		0xAFAFAFAA