/*
 * |>====================<|
 * |   About: Text list   |
 * |   Author: Foxze      |
 * |>====================<|
 */

#if defined _INC_TEXT_LIST
	#endinput
#endif
#define _INC_TEXT_LIST

/*
 * |>---------------<|
 * |     Defines     |
 * |>---------------<|
 */

#define T_ERROR			"[Ошибка]"
#define T_INFO			"[Инфо]"
#define T_CMD			"[Команда]"
#define T_HINT			"[Подсказка]"
#define T_PASS			"[Пароль]"
#define T_REPORT		"[Репорт]"
#define T_RANK			"[Ранг]"
#define T_EXP			"[EXP]"
#define T_REPLEN		"[Пополнение]"
#define T_PM			"[ЛС]"
#define T_BLACKLIST		"[Чёрный список]"
#define T_PREMIUM		"[Премиум]"
#define T_QUEST			"[Квест]"
#define T_ROOM			"[Комната]"
#define T_MATCH			"[Матч]"
#define T_TEAM			"[Команда]"
#define T_SQUAD			"[Отряд]"
#define T_RADIO			"[Рация]"
#define T_AIRDROP		"[Аирдроп]"
#define T_ABILITY		"[Способность]"
#define T_DINA			"[ Дина ]"
#define T_PID			"[ID:%i]"
#define T_NUM			"•"